apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  parallelism: 1000
  completions: 1000
  completionMode: Indexed
  template:
    spec:
      schedulingGroup:
        podGroupName: job-1-template
      containers:
      - name: sleep-container
        image: quay.io/quay/busybox:latest
        command: ["sleep", "10000"]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Never
  backoffLimit: 4
